### ISSUE TITLE
What happened to CED and DaSheng?

### ISSUE THREAD

**Issue by yuyun2000** [RicherMans/Speaker-Anti-Spoofing-Classifiers#5]
What happened? Why were CED and DaSheng repositories deleted? Are you leaving Xiaomi? I'm just concerned.

**Comment by RicherMans** [comment]
Hey,
thanks for your concerns! I appreciate that.

I didn't delete the Repos, they are currently just private.
The reason is that the models work for some products in the company a bit too well, so ... politics.
But approx. next week I should be able to make them public again, no worries.

Kind regards,
Heinrich

**Comment by RicherMans** [comment]
Update:
All online again, now even official:

![20240720-133058](https://github.com/user-attachments/assets/d33537f1-0b0b-413a-a936-8af56e89b36b)
